### ISSUE TITLE
how do you constrcut the ind_mat.txt

### ISSUE THREAD

**Issue by RunRungo** [CrickWu/DL4Epi#1]
hello  I do not understand how do you  construct ind_mat , can you explain ? Thanks

**Comment by RunRungo** [comment]
you said you construct the adjacency matrix G based on the real-world location of signals. what the location of signals mean?

**Comment by CrickWu** [comment]
We actually adopted a 0/1 neighborhood paradigm to construct the adjacency matrix. That is we initialize a n x n  matrix, where entry i, j is 1 if and only if node i and node j are physically adjacent to each other.

**Comment by RunRungo** [comment]
Thanks but I want to know  how do you konw node i and node j are physically adjacent ? Do you calulate the distance between node i and node j or something else? Could you tell me the process of whether the node i and node j are physically adjacent?  Thank you very much

**Comment by RunRungo** [comment]
if  node i and node j have boundary, you set node i and node j one . if they do not have boundary you set zero . Is that right about what I understand?

**Comment by CrickWu** [comment]
For the datasets we considered, the physical adjacency is a given property defined in maps. Two prefectures/states are adjacent if they share common physical borders. The way to set values of 0/1 is just as you have described.

**Comment by RunRungo** [comment]
看你名称你是中国学生 我在中国东南大学读计算机博士 研究方向也是流行病得预测 用深度学习方法 这个方向做的人好像不多 你有微信吗 可以加个微信多交流下吗



At 2019-11-08 09:31:54, "Yuexin Wu" <notifications@github.com> wrote:


For the datasets we considered, the physical adjacency is a given property defined in maps. Two prefectures/states are adjacent if they share common physical borders. The way to set values of 0/1 is just as you have described.

**Comment by CrickWu** [comment]
Sure, we certainly could discuss more over email and SNS. You could drop me a line to start the conversation.

**Comment by RunRungo** [comment]
ok
This is my WeChat  Looking forward to communicating with you




At 2019-11-08 22:26:43, "Yuexin Wu" <notifications@github.com> wrote:


Sure, we certainly could discuss more over email and SNS. You could drop me a line to start the conversation.

**Comment by CrickWu** [comment]
Probably you can send it to my personal email.

**Comment by RunRungo** [comment]
OK could you give me your personal email address?




At 2019-11-14 02:10:26, "Yuexin Wu" <notifications@github.com> wrote:


Probably you can send it to my personal email.

**Comment by CrickWu** [comment]
You could contact me at crickwu@gmail.com

**Comment by RunRungo** [comment]
Sorry  I could not understand what 3 2 0 1 mean? 






At 2019-11-19 10:01:26, "Yuexin Wu" <notifications@github.com> wrote:


You could contact me at crickwu@gmail.com
